### ISSUE TITLE
线上的版本是3.14.1，这个版本需要更新

### ISSUE THREAD

**Issue by crosswall** [leancloud/android-push-demo#3]
这个版本给我的误导：
sdk本身依赖了async-http-client，apach的httpcore、httpmime，以及fastjson，我认为SDK不应该有这么多的依赖
文档并没有对jar包冲突做出说明，这个坑肯定被很多人踩了。
我的解决方式：

``` code
compile ('cn.leancloud.android:avoscloud-sdk:v3.7.1'){
        exclude module:'httpmime';
        exclude module:'fastjson';
}
```

官方已经放弃httpClient了，实在不希望看到项目里既有okhttp又有async-http-client
这个PushDemo的上一次更新时间是11月以前，也是醉了。

最后：
为什么想用leancloud的Push方案？
你们的用户有Uber、知乎这样优秀的产品，实在很难阻挡我使用leancloud的sdk
感谢leancloud带来优质的MBaaS

**Comment by Uphie** [comment]
我也是同样的问题
